package net.jami.services

import net.jami.model.MediaAttribute
import net.jami.model.SwarmMessage

/**
 * Android implementation of DaemonBridge using SWIG-generated JNI bindings.
 *
 * This implementation wraps the JamiService class generated by SWIG from
 * jami-daemon/bin/jni/jni_interface.i
 *
 * TODO: Import and wire up the actual SWIG-generated classes:
 * - JamiService (main entry point)
 * - Callback, ConfigurationCallback, etc. (director classes for callbacks)
 */
actual class DaemonBridge actual constructor() {
    private var isInitialized = false
    private var callbacks: DaemonCallbacks? = null

    // TODO: Initialize SWIG callbacks
    // private val swigCallback = object : Callback() { ... }
    // private val swigConfigCallback = object : ConfigurationCallback() { ... }

    actual fun init(callbacks: DaemonCallbacks): Boolean {
        this.callbacks = callbacks

        // TODO: Uncomment when SWIG bindings are integrated
        // JamiService.init(swigCallback, swigConfigCallback, ...)

        isInitialized = true
        return true
    }

    actual fun start(): Boolean {
        // TODO: JamiService.start()
        return isInitialized
    }

    actual fun stop() {
        // TODO: JamiService.fini()
        isInitialized = false
    }

    actual fun isRunning(): Boolean = isInitialized

    // Account operations
    actual fun addAccount(details: Map<String, String>): String {
        // TODO: return JamiService.addAccount(details.toStringMap())
        return ""
    }

    actual fun removeAccount(accountId: String) {
        // TODO: JamiService.removeAccount(accountId)
    }

    actual fun getAccountDetails(accountId: String): Map<String, String> {
        // TODO: return JamiService.getAccountDetails(accountId).toKotlinMap()
        return emptyMap()
    }

    actual fun setAccountDetails(accountId: String, details: Map<String, String>) {
        // TODO: JamiService.setAccountDetails(accountId, details.toStringMap())
    }

    actual fun getAccountList(): List<String> {
        // TODO: return JamiService.getAccountList().toKotlinList()
        return emptyList()
    }

    actual fun setAccountActive(accountId: String, active: Boolean) {
        // TODO: JamiService.setAccountActive(accountId, active)
    }

    // Call operations
    actual fun placeCall(accountId: String, uri: String, mediaList: List<MediaAttribute>): String {
        // TODO: Convert mediaList to SWIG vector and call JamiService.placeCallWithMedia(...)
        return ""
    }

    actual fun accept(accountId: String, callId: String, mediaList: List<MediaAttribute>) {
        // TODO: JamiService.acceptWithMedia(accountId, callId, mediaList.toSwigVector())
    }

    actual fun hangUp(accountId: String, callId: String) {
        // TODO: JamiService.hangUp(accountId, callId)
    }

    actual fun hold(accountId: String, callId: String) {
        // TODO: JamiService.hold(accountId, callId)
    }

    actual fun unhold(accountId: String, callId: String) {
        // TODO: JamiService.unhold(accountId, callId)
    }

    actual fun muteLocalMedia(accountId: String, callId: String, mediaType: String, mute: Boolean) {
        // TODO: JamiService.muteLocalMedia(accountId, callId, mediaType, mute)
    }

    // Conversation operations
    actual fun getConversations(accountId: String): List<String> {
        // TODO: return JamiService.getConversations(accountId).toKotlinList()
        return emptyList()
    }

    actual fun startConversation(accountId: String): String {
        // TODO: return JamiService.startConversation(accountId)
        return ""
    }

    actual fun sendMessage(accountId: String, conversationId: String, message: String, replyTo: String, flag: Int) {
        // TODO: JamiService.sendMessage(accountId, conversationId, message, replyTo, flag)
    }

    actual fun loadConversation(accountId: String, conversationId: String, fromMessage: String, size: Int) {
        // TODO: JamiService.loadConversation(accountId, conversationId, fromMessage, size)
    }

    actual fun getConversationMembers(accountId: String, conversationId: String): List<Map<String, String>> {
        // TODO: return JamiService.getConversationMembers(accountId, conversationId).toKotlinListOfMaps()
        return emptyList()
    }

    // Contact operations
    actual fun addContact(accountId: String, uri: String) {
        // TODO: JamiService.addContact(accountId, uri)
    }

    actual fun removeContact(accountId: String, uri: String, ban: Boolean) {
        // TODO: JamiService.removeContact(accountId, uri, ban)
    }

    actual fun getContacts(accountId: String): List<Map<String, String>> {
        // TODO: return JamiService.getContacts(accountId).toKotlinListOfMaps()
        return emptyList()
    }

    // Name lookup
    actual fun lookupName(accountId: String, nameServiceUrl: String, name: String): Boolean {
        // TODO: return JamiService.lookupName(accountId, nameServiceUrl, name)
        return false
    }

    actual fun lookupAddress(accountId: String, nameServiceUrl: String, address: String): Boolean {
        // TODO: return JamiService.lookupAddress(accountId, nameServiceUrl, address)
        return false
    }

    actual fun registerName(accountId: String, name: String, scheme: String, password: String): Boolean {
        // TODO: return JamiService.registerName(accountId, name, scheme, password)
        return false
    }
}
