/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class Callback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Callback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_Callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    JamiServiceJNI.Callback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    JamiServiceJNI.Callback_change_ownership(this, swigCPtr, true);
  }

  public void callStateChanged(String accountId, String callId, String state, int detail_code) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_callStateChanged(swigCPtr, this, accountId, callId, state, detail_code); else JamiServiceJNI.Callback_callStateChangedSwigExplicitCallback(swigCPtr, this, accountId, callId, state, detail_code);
  }

  public void transferFailed() {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_transferFailed(swigCPtr, this); else JamiServiceJNI.Callback_transferFailedSwigExplicitCallback(swigCPtr, this);
  }

  public void transferSucceeded() {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_transferSucceeded(swigCPtr, this); else JamiServiceJNI.Callback_transferSucceededSwigExplicitCallback(swigCPtr, this);
  }

  public void recordPlaybackStopped(String path) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_recordPlaybackStopped(swigCPtr, this, path); else JamiServiceJNI.Callback_recordPlaybackStoppedSwigExplicitCallback(swigCPtr, this, path);
  }

  public void voiceMailNotify(String accountId, int newCount, int oldCount, int urgentCount) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_voiceMailNotify(swigCPtr, this, accountId, newCount, oldCount, urgentCount); else JamiServiceJNI.Callback_voiceMailNotifySwigExplicitCallback(swigCPtr, this, accountId, newCount, oldCount, urgentCount);
  }

  public void incomingMessage(String accountId, String callId, String from, StringMap messages) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_incomingMessage(swigCPtr, this, accountId, callId, from, StringMap.getCPtr(messages), messages); else JamiServiceJNI.Callback_incomingMessageSwigExplicitCallback(swigCPtr, this, accountId, callId, from, StringMap.getCPtr(messages), messages);
  }

  public void incomingCall(String accountId, String callId, String from, VectMap mediaList) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_incomingCall(swigCPtr, this, accountId, callId, from, VectMap.getCPtr(mediaList), mediaList); else JamiServiceJNI.Callback_incomingCallSwigExplicitCallback(swigCPtr, this, accountId, callId, from, VectMap.getCPtr(mediaList), mediaList);
  }

  public void mediaChangeRequested(String accountId, String callId, VectMap mediaList) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_mediaChangeRequested(swigCPtr, this, accountId, callId, VectMap.getCPtr(mediaList), mediaList); else JamiServiceJNI.Callback_mediaChangeRequestedSwigExplicitCallback(swigCPtr, this, accountId, callId, VectMap.getCPtr(mediaList), mediaList);
  }

  public void recordPlaybackFilepath(String id, String filename) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_recordPlaybackFilepath(swigCPtr, this, id, filename); else JamiServiceJNI.Callback_recordPlaybackFilepathSwigExplicitCallback(swigCPtr, this, id, filename);
  }

  public void conferenceCreated(String accountId, String conversationId, String confId) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_conferenceCreated(swigCPtr, this, accountId, conversationId, confId); else JamiServiceJNI.Callback_conferenceCreatedSwigExplicitCallback(swigCPtr, this, accountId, conversationId, confId);
  }

  public void conferenceChanged(String accountId, String confId, String state) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_conferenceChanged(swigCPtr, this, accountId, confId, state); else JamiServiceJNI.Callback_conferenceChangedSwigExplicitCallback(swigCPtr, this, accountId, confId, state);
  }

  public void conferenceRemoved(String accountId, String confId) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_conferenceRemoved(swigCPtr, this, accountId, confId); else JamiServiceJNI.Callback_conferenceRemovedSwigExplicitCallback(swigCPtr, this, accountId, confId);
  }

  public void updatePlaybackScale(String filepath, int position, int scale) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_updatePlaybackScale(swigCPtr, this, filepath, position, scale); else JamiServiceJNI.Callback_updatePlaybackScaleSwigExplicitCallback(swigCPtr, this, filepath, position, scale);
  }

  public void newCall(String accountId, String callId, String to) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_newCall(swigCPtr, this, accountId, callId, to); else JamiServiceJNI.Callback_newCallSwigExplicitCallback(swigCPtr, this, accountId, callId, to);
  }

  public void recordingStateChanged(String callId, int code) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_recordingStateChanged(swigCPtr, this, callId, code); else JamiServiceJNI.Callback_recordingStateChangedSwigExplicitCallback(swigCPtr, this, callId, code);
  }

  public void recordStateChange(String callId, int state) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_recordStateChange(swigCPtr, this, callId, state); else JamiServiceJNI.Callback_recordStateChangeSwigExplicitCallback(swigCPtr, this, callId, state);
  }

  public void onRtcpReportReceived(String callId, IntegerMap stats) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_onRtcpReportReceived(swigCPtr, this, callId, IntegerMap.getCPtr(stats), stats); else JamiServiceJNI.Callback_onRtcpReportReceivedSwigExplicitCallback(swigCPtr, this, callId, IntegerMap.getCPtr(stats), stats);
  }

  public void onConferenceInfosUpdated(String confId, VectMap infos) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_onConferenceInfosUpdated(swigCPtr, this, confId, VectMap.getCPtr(infos), infos); else JamiServiceJNI.Callback_onConferenceInfosUpdatedSwigExplicitCallback(swigCPtr, this, confId, VectMap.getCPtr(infos), infos);
  }

  public void peerHold(String callId, boolean holding) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_peerHold(swigCPtr, this, callId, holding); else JamiServiceJNI.Callback_peerHoldSwigExplicitCallback(swigCPtr, this, callId, holding);
  }

  public void audioMuted(String callId, boolean muted) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_audioMuted(swigCPtr, this, callId, muted); else JamiServiceJNI.Callback_audioMutedSwigExplicitCallback(swigCPtr, this, callId, muted);
  }

  public void videoMuted(String callId, boolean muted) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_videoMuted(swigCPtr, this, callId, muted); else JamiServiceJNI.Callback_videoMutedSwigExplicitCallback(swigCPtr, this, callId, muted);
  }

  public void connectionUpdate(String id, int state) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_connectionUpdate(swigCPtr, this, id, state); else JamiServiceJNI.Callback_connectionUpdateSwigExplicitCallback(swigCPtr, this, id, state);
  }

  public void remoteRecordingChanged(String callId, String peer_number, boolean state) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_remoteRecordingChanged(swigCPtr, this, callId, peer_number, state); else JamiServiceJNI.Callback_remoteRecordingChangedSwigExplicitCallback(swigCPtr, this, callId, peer_number, state);
  }

  public void mediaNegotiationStatus(String callId, String event, VectMap mediaList) {
    if (getClass() == Callback.class) JamiServiceJNI.Callback_mediaNegotiationStatus(swigCPtr, this, callId, event, VectMap.getCPtr(mediaList), mediaList); else JamiServiceJNI.Callback_mediaNegotiationStatusSwigExplicitCallback(swigCPtr, this, callId, event, VectMap.getCPtr(mediaList), mediaList);
  }

  @SuppressWarnings("this-escape")
  public Callback() {
    this(JamiServiceJNI.new_Callback(), true);
    JamiServiceJNI.Callback_director_connect(this, swigCPtr, true, true);
  }

}
