/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class FloatVect extends java.util.AbstractList<Float> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FloatVect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatVect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FloatVect obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_FloatVect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FloatVect(float[] initialElements) {
    this();
    reserve(initialElements.length);

    for (float element : initialElements) {
      add(element);
    }
  }

  public FloatVect(Iterable<Float> initialElements) {
    this();
    for (float element : initialElements) {
      add(element);
    }
  }

  public Float get(int index) {
    return doGet(index);
  }

  public Float set(int index, Float e) {
    return doSet(index, e);
  }

  public boolean add(Float e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Float e) {
    modCount++;
    doAdd(index, e);
  }

  public Float remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public FloatVect() {
    this(JamiServiceJNI.new_FloatVect__SWIG_0(), true);
  }

  public FloatVect(FloatVect other) {
    this(JamiServiceJNI.new_FloatVect__SWIG_1(FloatVect.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return JamiServiceJNI.FloatVect_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JamiServiceJNI.FloatVect_clear(swigCPtr, this);
  }

  public FloatVect(int count, float value) {
    this(JamiServiceJNI.new_FloatVect__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return JamiServiceJNI.FloatVect_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    JamiServiceJNI.FloatVect_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return JamiServiceJNI.FloatVect_doSize(swigCPtr, this);
  }

  private void doAdd(float x) {
    JamiServiceJNI.FloatVect_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, float x) {
    JamiServiceJNI.FloatVect_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private float doRemove(int index) {
    return JamiServiceJNI.FloatVect_doRemove(swigCPtr, this, index);
  }

  private float doGet(int index) {
    return JamiServiceJNI.FloatVect_doGet(swigCPtr, this, index);
  }

  private float doSet(int index, float val) {
    return JamiServiceJNI.FloatVect_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    JamiServiceJNI.FloatVect_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
