/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class NetworkServiceCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NetworkServiceCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetworkServiceCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NetworkServiceCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_NetworkServiceCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    JamiServiceJNI.NetworkServiceCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    JamiServiceJNI.NetworkServiceCallback_change_ownership(this, swigCPtr, true);
  }

  public void peerServicesReceived(long arg0, String arg1, String arg2, int arg3, String arg4) {
    if (getClass() == NetworkServiceCallback.class) JamiServiceJNI.NetworkServiceCallback_peerServicesReceived(swigCPtr, this, arg0, arg1, arg2, arg3, arg4); else JamiServiceJNI.NetworkServiceCallback_peerServicesReceivedSwigExplicitNetworkServiceCallback(swigCPtr, this, arg0, arg1, arg2, arg3, arg4);
  }

  public void serviceTunnelOpened(String arg0, String arg1, int arg2) {
    if (getClass() == NetworkServiceCallback.class) JamiServiceJNI.NetworkServiceCallback_serviceTunnelOpened(swigCPtr, this, arg0, arg1, arg2); else JamiServiceJNI.NetworkServiceCallback_serviceTunnelOpenedSwigExplicitNetworkServiceCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void serviceTunnelClosed(String arg0, String arg1, String arg2) {
    if (getClass() == NetworkServiceCallback.class) JamiServiceJNI.NetworkServiceCallback_serviceTunnelClosed(swigCPtr, this, arg0, arg1, arg2); else JamiServiceJNI.NetworkServiceCallback_serviceTunnelClosedSwigExplicitNetworkServiceCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public NetworkServiceCallback() {
    this(JamiServiceJNI.new_NetworkServiceCallback(), true);
    JamiServiceJNI.NetworkServiceCallback_director_connect(this, swigCPtr, true, true);
  }

}
