/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class SWIGTYPE_p_libjami__SinkTarget {
  private transient long swigCPtr;

  protected SWIGTYPE_p_libjami__SinkTarget(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_libjami__SinkTarget() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_libjami__SinkTarget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_libjami__SinkTarget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

